version: "3.8"
services:
  backend:
    volumes:
        - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
    networks:
      - backend-network

  pgdb:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend-network

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  backend-network:
    driver: bridge